Travis: use /tmp instead of /dev/shm for the shared heap
The /dev/shm is only 64MB on Travis container, tests fail with

Fatal error: exception Unix.Unix_error(Unix.ESPIPE, "fallocate", "")