[autocomplete] Fix crash on types with default arguments
Summary:
Attempting to autocomplete a property of a type with default type arguments results in the autocomplete command crashing:

given the file `poly.js`:
```
//flow

type T<S=number> = {x: S};
declare var a: T<>;
a.
```
flow crashes as below:

```
[.../flow/tests/autocomplete]$ flow autocomplete 5 3 < poly.js
Error: (Failure "cannot instantiate non-class type PolyT")
Raised at file "stdlib.ml", line 33, characters 17-33
Called from file ".../flow/src/typing/members.ml", line 373, characters 19-42
...
```
This occurred because the type parameter instantiation algorithm used by `members.ml` ignores default type arguments.

This diff replaces the algorithm with a simplified version of the algorithm used for "actual" type instantiation in `flow_js.ml`, which handles default arguments correctly.

Reviewed By: mroch

Differential Revision: D17175083

fbshipit-source-id: d4435a4f540ee7480ca5aacfeaeb16d7bb11af79