improve command errors
Summary: Missing arguments on the command line would result in
clowny uncaught Not_found exceptions with no additional
info. This improves the situation a bit, e.g.

Before:
```
$ flow get-def
Fatal error: exception Not_found
```

After:
```
$ flow get-def
flow: missing required arguments
Usage: flow get-def [OPTION]... [FILE] LINE COLUMN
...
```

Reviewed By: @avikchaudhuri

Differential Revision: D2069391