Never pick errors from the sentinel prop in union speculation
Summary:
This diff simplifies error messages for programs like:

```
type X =
  | {type: 'A', p: number}
  | {type: 'B', p: string}
  | {type: 'C', p: boolean};

({type: 'A', p: 'foo'}: X);
```

An error which used to be:

```
Error: /home/calebmer/__playground__/flow/test.js:11
 11: ({type: 'A', p: 'foo'}: X);
      ^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
 11: ({type: 'A', p: 'foo'}: X);
                             ^ union: object type(s)
  Member 1:
    7:   | {type: 'A', p: number}
           ^^^^^^^^^^^^^^^^^^^^^^ object type
  Error:
   11: ({type: 'A', p: 'foo'}: X);
        ^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
    7:   | {type: 'A', p: number}
           ^^^^^^^^^^^^^^^^^^^^^^ object type
    Property `p` is incompatible:
       11: ({type: 'A', p: 'foo'}: X);
                           ^^^^^ string. This type is incompatible with
        7:   | {type: 'A', p: number}
                              ^^^^^^ number
  Member 2:
    8:   | {type: 'B', p: string}
           ^^^^^^^^^^^^^^^^^^^^^^ object type
  Error:
   11: ({type: 'A', p: 'foo'}: X);
        ^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
    8:   | {type: 'B', p: string}
           ^^^^^^^^^^^^^^^^^^^^^^ object type
    Property `type` is incompatible:
       11: ({type: 'A', p: 'foo'}: X);
                   ^^^ string. Expected string literal `B`, got `A` instead
        8:   | {type: 'B', p: string}
                      ^^^ string literal `B`
  Member 3:
    9:   | {type: 'C', p: boolean};
           ^^^^^^^^^^^^^^^^^^^^^^^ object type
  Error:
   11: ({type: 'A', p: 'foo'}: X);
        ^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
    9:   | {type: 'C', p: boolean};
           ^^^^^^^^^^^^^^^^^^^^^^^ object type
    Property `type` is incompatible:
       11: ({type: 'A', p: 'foo'}: X);
                   ^^^ string. Expected string literal `C`, got `A` instead
        9:   | {type: 'C', p: boolean};
                      ^^^ string literal `C`
```

Is now:

```
Error: test.js:11
 11: ({type: 'A', p: 'foo'}: X);
      ^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
  7:   | {type: 'A', p: number}
         ^^^^^^^^^^^^^^^^^^^^^^ object type
  Property `p` is incompatible:
     11: ({type: 'A', p: 'foo'}: X);
                         ^^^^^ string. This type is incompatible with
      7:   | {type: 'A', p: number}
                            ^^^^^^ number
```

We accomplish this by building off the score machinery in the previous diff.

We greatly punish the score of errors who failed their sentinel prop checks. This causes them to disappear from the message.

Reviewed By: gabelevi

Differential Revision: D6442965

fbshipit-source-id: 7c4e174d8720b721dd4a24e2dd19cbd6b5842e30