adds a missing mandatory step in opam how-to
Otherwise, one gets a dirty:

    # + ocamlopt   -ccopt -DNO_LZ4 -c hack/hhi/hhi_elf.c
    # hack/hhi/hhi_elf.c:26:18: fatal error: gelf.h: No such file or directory
    # compilation terminated.
    # Command exited with code 2. 
    # Makefile:131: recipe for target 'build-flow-native-deps' failed  
    ### stderr ###
    # abort: there is no Mercurial repository here (.hg not found)
    # make: *** [build-flow-native-deps] Error 10