[hack] Error on overriding concrete type constant with an abstract one
Summary: This is a runtime error, but the typechecker would permit it:

  [~/fbcode] php  hphp/hack/test/typecheck/tconst/subsume_tconst5.php

  Fatal error: Cannot re-declare as abstract previously defined type constant PartiallyAbstract::T2 in FullyAbstract in hphp/hack/test/typecheck/tconst/subsume_tconst5.php on line 8

Note: we are also missing a similar check for abstract functions:

  class X {
    public function f(): void {}
  }

  abstract class Y extends X {
    abstract public function f(): void;
  }

but the code for checking type constants and functions is not shared, so this diff is fixing only one of them.

Reviewed By: @dlreeves

Differential Revision: D2237726