[PR] Bump rubyzip from 1.2.2 to 1.3.0 in /website
Summary:
Bumps [rubyzip](https://github.com/rubyzip/rubyzip) from 1.2.2 to 1.3.0.
<details>
<summary>Release notes</summary>

*Sourced from [rubyzip's releases](https://github.com/rubyzip/rubyzip/releases).*

> ## v1.3.0
> Security
>
> - Add `validate_entry_sizes` option so that callers can trust an entry's reported size when using `extract` [https://github.com/facebook/flow/issues/403](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/403)
>    - This option defaults to `false` for backward compatibility in this release, but you are strongly encouraged to set it to `true`. It will default to `true` in rubyzip 2.0.
>
> New Feature
>
> - Add `add_stored` method to simplify adding entries without compression [https://github.com/facebook/flow/issues/366](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/366)
>
> Tooling / Documentation
>
> - Add more gem metadata links [https://github.com/facebook/flow/issues/402](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/402)
>
> ## v1.2.4
> - Do not rewrite zip files opened with `open_buffer` that have not changed [https://github.com/facebook/flow/issues/360](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/360)
>
> Tooling / Documentation
>
> - Update `example_recursive.rb` in README [https://github.com/facebook/flow/issues/397](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/397)
> - Hold CI at `trusty` for now, automatically pick the latest ruby patch version, use rbx-4 and hold jruby at 9.1 [https://github.com/facebook/flow/issues/399](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/399)
>
> ## v1.2.3
> * Allow tilde in zip entry names [https://github.com/facebook/flow/issues/391](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/391) (fixes regression in 1.2.2 from [https://github.com/facebook/flow/issues/376](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/376))
> * Support frozen string literals in more files [https://github.com/facebook/flow/issues/390](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/390)
> * Require `pathname` explicitly [https://github.com/facebook/flow/issues/388](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/388) (fixes regression in 1.2.2 from [https://github.com/facebook/flow/issues/376](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/376))
>
> Tooling / Documentation:
>
> * CI updates [https://github.com/facebook/flow/issues/392](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/392), [https://github.com/facebook/flow/issues/394](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/394)
>    * Bump supported ruby versions and add 2.6
>    * JRuby failures are no longer ignored (reverts [https://github.com/facebook/flow/issues/375](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/375) / part of [https://github.com/facebook/flow/issues/371](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/371))
> * Add changelog entry that was missing for last release [https://github.com/facebook/flow/issues/387](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/387)
> * Comment cleanup [https://github.com/facebook/flow/issues/385](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/385)
>
> Since the GitHub release information for 1.2.2 is missing, I will also include it here:
>
> ### 1.2.2
>
> NB: This release drops support for extracting symlinks, because there was no clear way to support this securely. See https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/376#issue-210954555 for details.
>
> * Fix CVE-2018-1000544 [https://github.com/facebook/flow/issues/376](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/376) / [https://github.com/facebook/flow/issues/371](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/371)
> * Fix NoMethodError: undefined method `glob' [https://github.com/facebook/flow/issues/363](https://github.com/rubyzip/rubyzip/pull/363)
> * Fix handling of stored files (i.e. files not using compression) with general purpose bit 3 set [https://github.com/facebook/flow/issues/358](https://github.com/rubyzip/rubyzip/pull/358)
> * Fix `close` on StringIO-backed zip file [https://github.com/facebook/flow/issues/353](https://github.com/rubyzip/rubyzip/pull/353)
> * Add `Zip.force_entry_names_encoding` option [https://github.com/facebook/flow/issues/340](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/340)
> * Update rubocop, apply auto-fixes, and fix regressions caused by said auto-fixes [https://github.com/facebook/flow/issues/332](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/332), [https://github.com/facebook/flow/issues/355](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/355)
> * Save temporary files to temporary directory (rather than current directory) [https://github.com/facebook/flow/issues/325](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/325)
>
> Tooling / Documentation:
></tr></table> ... (truncated)
</details>
<details>
<summary>Changelog</summary>

*Sourced from [rubyzip's changelog](https://github.com/rubyzip/rubyzip/blob/master/Changelog.md).*

> # 1.3.0 (2019-09-25)
>
> Security
>
> - Add `validate_entry_sizes` option so that callers can trust an entry's reported size when using `extract` [https://github.com/facebook/flow/issues/403](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/403)
>    - This option defaults to `false` for backward compatibility in this release, but you are strongly encouraged to set it to `true`. It will default to `true` in rubyzip 2.0.
>
> New Feature
>
> - Add `add_stored` method to simplify adding entries without compression [https://github.com/facebook/flow/issues/366](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/366)
>
> Tooling / Documentation
>
> - Add more gem metadata links [https://github.com/facebook/flow/issues/402](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/402)
>
> # 1.2.4 (2019-09-06)
>
> - Do not rewrite zip files opened with `open_buffer` that have not changed [https://github.com/facebook/flow/issues/360](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/360)
>
> Tooling / Documentation
>
> - Update `example_recursive.rb` in README [https://github.com/facebook/flow/issues/397](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/397)
> - Hold CI at `trusty` for now, automatically pick the latest ruby patch version, use rbx-4 and hold jruby at 9.1 [https://github.com/facebook/flow/issues/399](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/399)
>
> # 1.2.3
>
> - Allow tilde in zip entry names [https://github.com/facebook/flow/issues/391](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/391) (fixes regression in 1.2.2 from [https://github.com/facebook/flow/issues/376](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/376))
> - Support frozen string literals in more files [https://github.com/facebook/flow/issues/390](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/390)
> - Require `pathname` explicitly [https://github.com/facebook/flow/issues/388](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/388) (fixes regression in 1.2.2 from [https://github.com/facebook/flow/issues/376](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/376))
>
> Tooling / Documentation:
>
> - CI updates [https://github.com/facebook/flow/issues/392](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/392), [https://github.com/facebook/flow/issues/394](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/394)
>   - Bump supported ruby versions and add 2.6
>   - JRuby failures are no longer ignored (reverts [https://github.com/facebook/flow/issues/375](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/375) / part of [https://github.com/facebook/flow/issues/371](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/371))
> - Add changelog entry that was missing for last release [https://github.com/facebook/flow/issues/387](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/387)
> - Comment cleanup [https://github.com/facebook/flow/issues/385](https://github-redirect.dependabot.com/rubyzip/rubyzip/pull/385)
</details>
<details>
<summary>Commits</summary>

- [`e79d9ea`](https://github.com/rubyzip/rubyzip/commit/e79d9ea2922be12db121c20f5dc55bba8a35418a) Merge pull request [https://github.com/facebook/flow/issues/407](https://github-redirect.dependabot.com/rubyzip/rubyzip/issues/407) from rubyzip/v1-3-0
- [`7c65e1e`](https://github.com/rubyzip/rubyzip/commit/7c65e1e3595031392f1050b81fb2b95b0f2ee764) Bump version to 1.3.0
- [`d65fe7b`](https://github.com/rubyzip/rubyzip/commit/d65fe7bd283ec94f9d6dc7605f61a6b0dd00f55e) Merge pull request [https://github.com/facebook/flow/issues/403](https://github-redirect.dependabot.com/rubyzip/rubyzip/issues/403) from rubyzip/check-size
- [`97cb6ae`](https://github.com/rubyzip/rubyzip/commit/97cb6aefe6d12bd2429d7a2e119ccb26f259d71d) Warn when an entry size is invalid
- [`7849f73`](https://github.com/rubyzip/rubyzip/commit/7849f7362ab0cd23d5730ef8b6f2c39252da2285) Default validate_entry_sizes to false for 1.3 release
- [`4167f0c`](https://github.com/rubyzip/rubyzip/commit/4167f0ce67e42b082605bca75c7bdfd01eb23804) Validate entry sizes when extracting
- [`94b7fa2`](https://github.com/rubyzip/rubyzip/commit/94b7fa276992933592d69eb6bb17fc09105f8395) [ci skip] Update changelog
- [`93505ca`](https://github.com/rubyzip/rubyzip/commit/93505ca16f0444bdb04f88f4b8f820ae5d628353) Check expected entry size in add_stored test
- [`6619bf3`](https://github.com/rubyzip/rubyzip/commit/6619bf3a1d779f092481d37d84ea280e3c6f764f) Merge pull request [https://github.com/facebook/flow/issues/366](https://github-redirect.dependabot.com/rubyzip/rubyzip/issues/366) from hainesr/add-stored
- [`ecb2776`](https://github.com/rubyzip/rubyzip/commit/ecb277621852589ecc1557f228665a5338ac0809) Zip::File.add_stored() to add uncompressed files.
- Additional commits viewable in [compare view](https://github.com/rubyzip/rubyzip/compare/v1.2.2...v1.3.0)
</details>
<br />

[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rubyzip&package-manager=bundler&previous-version=1.2.2&new-version=1.3.0)](https://help.github.com/articles/configuring-automated-security-fixes)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

 ---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `dependabot rebase` will rebase this PR
- `dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `dependabot merge` will merge this PR after your CI passes on it
- `dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `dependabot cancel merge` will cancel a previously requested merge and block automerging
- `dependabot reopen` will reopen this PR if it is closed
- `dependabot ignore this [patch|minor|major] version` will close this PR and stop Dependabot creating any more for this minor/major version (unless you reopen the PR or upgrade to it yourself)
- `dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language

You can disable automated security fix PRs for this repo from the [Security Alerts page](https://github.com/facebook/flow/network/alerts).

</details>
Pull Request resolved: https://github.com/facebook/flow/pull/8147

Differential Revision: D18120615

Pulled By: nmote

fbshipit-source-id: 8bb7feb00ca2f10db52fbf16dc1939dad3557856