Simplify speculation error messages
Summary:
This diff simplifies speculation error messages by assigning relative scores to each error message resulting from speculation and picking the messages with the highest score.

See the test suite for some compelling examples. One such example comes from `Date`. The following code:

```
new Date(2015, '6');
```

Used to produce the following error message

```
Error: date.js:19
 19: new Date(2015, '6');
     ^^^^^^^^^^^^^^^^^^^ new `Date`. Function cannot be called on any member of intersection type
 19: new Date(2015, '6');
         ^^^^ intersection
  Member 1:
  366:     constructor(): void;
           ^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:366
  Error:
   19: new Date(2015, '6');
                ^^^^ unused function argument. No arguments are expected by
  366:     constructor(): void;
           ^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:366
  Member 2:
  367:     constructor(timestamp: number): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:367
  Error:
   19: new Date(2015, '6');
                      ^^^ unused function argument. No more than 1 argument is expected by
  367:     constructor(timestamp: number): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:367
  Member 3:
  368:     constructor(dateString: string): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:368
  Error:
   19: new Date(2015, '6');
                      ^^^ unused function argument. No more than 1 argument is expected by
  368:     constructor(dateString: string): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:368
  Member 4:
  369:     constructor(year: number, month: number, day?: number, hour?: number, minute?: number, second?: number, millisecond?: number): void;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: <BUILTINS>/core.js:369
  Error:
   19: new Date(2015, '6');
                      ^^^ string. This type is incompatible with the expected param type of
  369:     constructor(year: number, month: number, day?: number, hour?: number, minute?: number, second?: number, millisecond?: number): void;
                                            ^^^^^^ number. See lib: <BUILTINS>/core.js:369
```

That message is pretty big and difficult to read. After this diff the error message will be:

```
Error: date.js:19
 19: new Date(2015, '6');
                    ^^^ string. This type is incompatible with the expected param type of
369:     constructor(year: number, month: number, day?: number, hour?: number, minute?: number, second?: number, millisecond?: number): void;
                                          ^^^^^^ number. See lib: <BUILTINS>/core.js:369
```

Concise and to the point. You could not tell the difference between this intersection error and any other error message you would get in yoru day-to-day interactions with Flow.

Before you continue to read this diff and assess my approach, I'd like to make the following claim:

**There is no principled way to pick the errors which are most relevant to humans.**

Some ideas have been floated around in the past. Most recently we've discussed using a fuzzy string matcher on printed types. It is very hard to devise a principled solution to this problem that works well in most cases. If you can think of a more principled way to accomplish what I've done with this diff, I desperately want to hear it\!

So instead we must apply *design thinking* to this problem. We know that our current error messages in almost every case show the user way to much information. So how do we *design* our error messages to show the user the most relevant information while still rejecting all programs that we currently reject.

We must also balance the design we desire with the actual tools available today, or the tools which can be built in a reasonable amount of time. (I'm talking about `use_op`s and reasons.)

The approach I took in this diff is to take each error message thrown during speculation, assign that error message an arbitrary score, and then only show the errors with the highest score.

Let us walk through how this works with the following program:

```
type X = string | {p: string};
(42: X);
({p: 42}: X);
```

If we just look at `({p: 42}: X)`, Flow's speculation will throw an error for both branches of the union.

- One error for `object ~> string`.
- A second error for `number ~> string`. (With a `use_op` that says we are in property `p`.)

The next step is to assign a score to each error. For this error we would use the `use_op` to determine a score. The first error has no `use_op` so we give it a score of 0. The second error does however have a `use_op` so we give it a score of 1. Since the second error has a higher score, we throw away the first error and only show the second. This results in the error:

```
Error: union.js:22
 22: ({p: 42}: B);
      ^^^^^^^ object literal. This type is incompatible with
 20: type B = string | {p: string};
                       ^^^^^^^^^^^ object type
  Property `p` is incompatible:
     22: ({p: 42}: B);
              ^^ number. This type is incompatible with
     20: type B = string | {p: string};
                               ^^^^^^ string
```

Previously the error we would give the user was twice as large!

```
Error: test.js:7
  7: ({p: 42}: X);
      ^^^^^^^ object literal. This type is incompatible with
  7: ({p: 42}: X);
               ^ union: string | object type
  Member 1:
    6: type X = string | {p: string};
                ^^^^^^ string
  Error:
    7: ({p: 42}: X);
        ^^^^^^^ object literal. This type is incompatible with
    6: type X = string | {p: string};
                ^^^^^^ string
  Member 2:
    6: type X = string | {p: string};
                         ^^^^^^^^^^^ object type
  Error:
    7: ({p: 42}: X);
        ^^^^^^^ object literal. This type is incompatible with
    6: type X = string | {p: string};
                         ^^^^^^^^^^^ object type
    Property `p` is incompatible:
        7: ({p: 42}: X);
                ^^ number. This type is incompatible with
        6: type X = string | {p: string};
                                 ^^^^^^ string
```

The way I describe this "score" in code comments is as:

> A relative metric for determining how close a given error is to the user's true intent for their program. Where 0 means we have no signal, where any positive number means we believe the error is close, and where any negative number means we have signal to strongly believe this is not what the user meant.

Note the words *user's true intent*. Determining the user's intent requires that we enter the user's mindset and consider how they practically use our type checker or what their expectations are for their programs.

Following are all the technical signals we use for calculating the score:

- `use_op` depth. This heuristic provides powerful signal for how much type checking Flow performed before arriving at our error. The more type-checking Flow does, the safer we can be assuming we are close to the user's intent. `TypeArgCompatibility` and `TupleElementCompatibility` provide much more signal then `PropertyCompatibility`. There are a few other special cases we consider for `use_op`s.
- The "kind" relationship of two types in an incompatibility. We use reason descriptions for this. For example, we give `number ~> string` a higher score then `number ~> {p: string}` because a scalar type (like `number`) to a composite type (like `{p: string}`) is further from the user's intent then say a composite type to a composite type (e.g. `{p: number} ~> {p: string}`). We implement this heuristic for scalars (`number`, `string`, `null`, `undefined`, etc.) and arrays seperately (arrays, read-only-arrays, tuples, rest, etc.). Since we use reasons for this test there isn't much more we can do. If the first heuristic prefers complex errors for compound types, this heuristic prefers simple errors for scalar types.

There are also a bunch of special cases where either the `use_op`s, reasons, or error messages don't exactly give us the information we would expect.

Score is represented as an integer which we add to and subtract from when we find signals. There are some signals which are much stronger then others. We put the amounts with which each signal increments the score on an `x^2` scale. This isn't perfect and can hypothetically lead to some awkward choices. I'm open to a better implementation of scores. One way to lower the propability of awkward choices is to increment the `n` in `x^n`.

(This diff does not intelligently handle sentinel props. See the next diff for better errors on tagged unions.)

Reviewed By: gabelevi

Differential Revision: D6442957

fbshipit-source-id: d158cc7f57687f134935be3a8e21bf4915e59717