Filter libraries and built-ins from flowtool suppressions
Summary:
Before this diff, flow tool add-comments attempts to add suppresions to library files, causing errors such as:

```
Error: ENOENT: no such file or directory, open '~/my/repo/[LIB] react.js'
```

This diff introduces a filter to only consider source files for suppression.

Reviewed By: gabelevi

Differential Revision: D13343627

fbshipit-source-id: 4a8f40e45fc3c6da96d823a179b67b7f8919ea01