Add `cursorTo` & `clearLine` to streams
Summary:
Using `process.stdout.cursorTo` and `process.stdout.clearLine` will error in Flow because those definitions are missing.

```bash
Error: src/db/seeds/utils/helpers.js:9
  9:   process.stdout.cursorTo(0)
                      ^^^^^^^^ property `cursorTo`. Property not found in
  9:   process.stdout.cursorTo(0)
       ^^^^^^^^^^^^^^ stream$Writable

Error: src/db/seeds/utils/helpers.js:9
  9:   process.stdout.cursorTo(0)
                      ^^^^^^^^ property `cursorTo`. Property not found in
  9:   process.stdout.cursorTo(0)
       ^^^^^^^^^^^^^^ tty$WriteStream
```
[node/lib/readline.js](https://github.com/nodejs/node/blob/4a276cc2a960b3f9a138ac3a99c9249a63b4d472/lib/readline.js#L1061-L1080)
[node/lib/tty.js](https://github.com/nodejs/node/blob/8bf48bf2cf714125fef91fd0651d3517b8953034/lib/tty.js#L131-L134)

```bash
Error: src/db/seeds/utils/helpers.js:10
 10:   process.stdout.clearLine()
                      ^^^^^^^^^ property `clearLine`. Property not found in
 10:   process.stdout.clearLine()
       ^^^^^^^^^^^^^^ stream$Writable

Error: src/db/seeds/utils/helpers.js:10
 10:   process.stdout.clearLine()
                      ^^^^^^^^^ property `clearLine`. Property not found in
 10:   process.stdout.clearLine()
       ^^^^^^^^^^^^^^ tty$WriteStream
```
[node/lib/readline.js](https://github.com/nodejs/node/blob/4a276cc2a960b3f9a138ac3a99c9249a63b4d472/lib/readline.js#L1103-L1124)
[node/lib/tty.js](https://github.com/nodejs/node/blob/8bf48bf2cf714125fef91fd0651d3517b8953034/lib/tty.js#L139-L142)

I'm not sure if I added them in the correct place, so please check and let me know.

Pull Request resolved: https://github.com/facebook/flow/pull/7082

Reviewed By: panagosg7

Differential Revision: D26883834

Pulled By: mroch

fbshipit-source-id: fb9ecffa8dafb250538a091a57ab454706effe24