fix fatal warning build failure for 4.04.1 compiler
Summary:
This warning causes `make` to fail for `4.04.1`. Looks like the module can be safely removed.

```
File "src/commands/ideCommand.ml", line 238, characters 2-71:
Warning 60: unused module IntMap.
File "src/commands/ideCommand.ml", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
Command exited with code 2.
Compilation unsuccessful after building 390 targets (0 cached) in 00:00:20.
make: *** [build-flow] Error 10
```

Reviewed By: mroch

Differential Revision: D5174631

fbshipit-source-id: 268f86cfca99cd96de035bf2b3e72c19c253ee6a