Fix open source builds after sqlite work
Summary:
`CAMLparam0()` declares `caml__frame`, so if you forget it, you get errors like

```
hh_shared.c:2130:3: error: use of undeclared identifier 'caml__frame'; did you mean 'caml_raise'?
  CAMLreturn(Val_long(0));
  ^
/Users/glevi/.opam/4.02.1/lib/ocaml/caml/memory.h:231:28: note: expanded from macro 'CAMLreturn'
                           ^
/Users/glevi/.opam/4.02.1/lib/ocaml/caml/memory.h:227:22: note: expanded from macro 'CAMLreturnT'
  caml_local_roots = caml__frame; \
```

And for ocp-build, we just need to set the `NO_SQLITE3` flag
Closes https://github.com/facebook/flow/pull/2733

Reviewed By: oulgen

Differential Revision: D4113588

Pulled By: gabelevi

fbshipit-source-id: c5f3e010bdc9c93f67469c0753c4986e931f5fff